(ns presentation-generator.model.presentation
  (:require [clj-time [core :as time] [coerce :as coerce]])
  (:import java.util.UUID))

(defrecord Presentation [upDatedOn presentationData script recordingStarted audioRecorded authors audioId summary])
(defrecord PresentationData [keyVals templateName])
(defn get-new-presentation ([presentationData summary]
  (Presentation. (coerce/to-date (time/now))
    presentationData {} (coerce/to-date (time/now))
    "mute" [{:username "autogenerated-nlp@sokratik.com"}]
    (str (UUID/randomUUID)) summary))
  ([presentationData]
    (get-new-presentation presentationData "")))

(defn get-presentation-data [keyVals templateName]
  (PresentationData. keyVals templateName))

